version: "3.9"
services:
  swap-skills:
    image: postgres:17
    restart: always
    container_name: swap-skills
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: